name: Lint and build

on:
  workflow_dispatch:  # This event will only trigger a workflow run if the workflow file exists on the default branch.
  release:
    types:
      - created  # Trigger on new GitHub release (for Docker build)

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download Go Modules
        run: go mod download

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

      - name: Run golangci-lint
        run: |
          $(go env GOPATH)/bin/golangci-lint run --timeout 3m

  build:
    name: Build and Publish Go Binary
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to create a release and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # or your preferred version

      - name: Set env variables
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build binaries for multiple OS/ARCH
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64   go build -o dist/tg-cmd-notify-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/tg-cmd-notify-windows-amd64.exe
          GOOS=darwin GOARCH=amd64  go build -o dist/tg-cmd-notify-darwin-amd64
          GOOS=darwin GOARCH=arm64  go build -o dist/tg-cmd-notify-darwin-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/tg-cmd-notify-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
